### ISSUE TITLE
How to handle errors?

### ISSUE THREAD

**Issue by nlw0** [MfgLabs/commons-aws#10]
I am trying to work with this library, and it has been awesome by the way, but I am a bit lost with how to handle errors. I was perfectly able to read S3 files using `getFileAsStream`. But now I am trying to handle errors. For instance, when a file is non-existent. I am writing an `ActorSubscriber` to work as a sink to the file stream. The problem is that I don't get an exception when the stream is created with `builder.getFileAsStream(...)`, I can't catch the exception in the stream `runWith`, and there is also no `OnError` message arriving at the actor sink. The exception is being thrown by some low-level AWS library and then catched by some actor, and all I get is a message like:

[ERROR] [07/22/2015 17:00:55.446] [Main-akka.actor.default-dispatcher-5] [akka://Main/user/app/$a/flow-1-7-singleSource-actorSubscriberSink] com.amazonaws.services.s3.model.AmazonS3Exception: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: BB8A57CBE63E1019E), S3 Extended Request ID: ibmciwv90sG0jqdj27s557NJGgBGci+oSsM1mfYkAnKJwaLgq+2pfd9c5WLhWhdk68su5i7Kx40= WARNING arguments left: 1

How could I treat this and other errors in my program?

**Comment by atamborrino** [comment]
Hi,

I think your issue comes from the way you wrote your ActorSubscriber, because if we test the following simple code: 

```scala
val source = streamBuilder.getFileAsStream(bucket, "foo")
val futBytes: Future[ByteString] = source.runFold(ByteString.empty)(_ ++ _)
```

```futBytes``` is completed with the following exception: ```com.amazonaws.services.s3.model.AmazonS3Exception, with message: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: 5171BBFD9D9B0B3F)```

**Comment by nlw0** [comment]
I'm not sure what else could I do except catching the `OnError` message, which is not being received. When you run the stream with an actor sink, it returns an `ActorRef`, not a `Future`. I think although the exception is successfully caught in your example, for some reason in my case it is not becoming an error signal that can travel all the way down to the actor sink. Unless my code is broken, this should be a problem specific for an `ActorSubscriber` sink.
