### ISSUE TITLE
Akka Streams 2.0

### ISSUE THREAD

**Issue by pkinsky** [MfgLabs/commons-aws#14]
The Akka Streams 2.0 release is out, and I was just wondering if you intend to update this project to use it. I understand this project relies on a bunch of custom stages, and migrating them to the new GraphStage will be a bit time consuming. If you're open to outside help maybe I can lend a hand.

**Comment by pkinsky** [comment]
After looking at the implementation of `uploadStreamAsFile`, let me just say that I have a whole new appreciation for the amount of work that went into this library.

**Comment by dmnpignaud** [comment]
Updating this project to use Akka-stream 2.0 is definitely something to do.
We will try to work on this as soon as possible !
Thank you for the appreciation :)
