### ISSUE TITLE
Something is spinning without terminating with S3StreamBuilder.uploadStreamAsFile

### ISSUE THREAD

**Issue by joearasin** [MfgLabs/commons-aws#16]
My stream is running, and completing, but then something is spinning for a minute after I shut down the ActorSystem before the process terminates. I'm not sure what is keeping the process alive, though.

**Comment by joearasin** [comment]
FWIW, it's basically a "Hello World" triggering this:

```
  implicit val system = ActorSystem()
  implicit val materializer = ActorMaterializer(ActorMaterializerSettings(system).withDebugLogging(true))
  implicit val ec = system.dispatcher

  val streamBuilder = S3StreamBuilder(new s3.AmazonS3AsyncClient())

  val awsFlow = streamBuilder.uploadStreamAsFile("MY_BUCKET_NAME","MY_KEY_NAME")

  Source.single("Hello")
    .map(ByteString(_))
    .via(awsFlow)
    .runWith(Sink.ignore)
    .flatMap { case _ =>
      println("Done!")
      system.terminate()
    }
```

**Comment by joearasin** [comment]
If I were to hazard a guess, I think `AmazonS3AsyncClient` is leaking threads.

**Comment by joearasin** [comment]
Ok. The caveat with this is that the proper solution is probably to actually submit a patch to aws-wrap to make the library properly extensible (and maybe to actually include the extension methods in the library), because this is clearly a hack. But it works.

**Comment by joearasin** [comment]
Mentioning this to keep an eye on: https://github.com/dwhjames/aws-wrap/pull/48

**Comment by Timshel** [comment]
Ok I just looked at this, from what I understand the delay is due to the `ThreadPoolExecutor.keepAliveTime` the idle thread are not immediately stopped preventing the application from stopping.

The `AmazonS3AsyncClient` inherit from `AmazonS3ScalaClient` the `shutdown` function which allow to shutdown the `AmazonS3Client` and the `ExecutorService`. 

Your example with the additional `shutdown` call will stop immediately : 
```
    Source.single("Hello")
      .map(ByteString(_))
      .via(awsFlow)
      .runWith(Sink.ignore)
      .flatMap { case _ =>
        println("Done!")
        client.shutdown()
        system.terminate()
      }
```
