### ISSUE TITLE
Deprecate / Remove uploadFile from S3

### ISSUE THREAD

**Issue by joearasin** [MfgLabs/commons-aws#18]
It probably doesn't make sense to have uploadFile default to PublicReadWrite ACL by default / without ability to be changed, and without it, the underlying library has an identical method: https://github.com/dwhjames/aws-wrap/blob/master/src/main/scala/s3/s3.scala#L518

**Comment by Timshel** [comment]
I finally did some cleanup, thx for your feedback.
