### ISSUE TITLE
Update to latest akka-stream-extensions

### ISSUE THREAD

**Issue by malcolmgreaves** [MfgLabs/commons-aws#19]
Hello!

Is there any work being done to bring this library up to date with the latest, stable version of akka? (2.4.x) Currently, this project depends on akka_streams_experimental 1.0 -- akka streams is long out of the experimental stage. This dependency is quite old and has several API inconsistencies with the 2.4.x.

I see that akka-stream-extensions version 0.10.0 depends on this updated akka streams version. However, 0.10.0 is not published (there's an issue for this: https://github.com/MfgLabs/akka-stream-extensions/issues/20).

Is there an ETA that the maintainers have for updating to Akka streams 2.4.x ?

Thank you for your work!

-m

**Comment by malcolmgreaves** [comment]
(If accepted) resolved by PR #20

**Comment by Voltir** [comment]
PR #20 appears to be merged, but I think a new version of common-aws needs to be published still - any plans to get that resolved?

**Comment by Timshel** [comment]
I just released the `0.10.0`, sorry for the delay.
