### ISSUE TITLE
Question on implementing back pressure

### ISSUE THREAD

**Issue by hardvain** [MfgLabs/commons-aws#21]
Hi, I see that in s3stream, getting the list of files in a buucket gets all the values and sends it as a stream to the downstream component. Suppose if the downstream component is not ready to accept the data, how the back pressure is handled here?

**Comment by Timshel** [comment]
`listFilesAsStream` was rewritten using `Source.unfoldAsync`, when backpressure happens it will stop calling `listNextBatchOfObjects`
