### ISSUE TITLE
DynamoDB Support

### ISSUE THREAD

**Issue by nemccarthy** [MfgLabs/commons-aws#22]
Any chance you guys might be adding DynamoDB support to this library soon?

**Comment by Timshel** [comment]
We are not using it so no.

**Comment by jto** [comment]
Hi @nemccarthy,
As @Timshel pointed out, we currently have no plan to add dynamo DB to the library. 
However, a pull request adding its support would be absolutely appreciated :) 
Let us know if you wish to contribute.
Cheers
