### ISSUE TITLE
Current AmazonS3AsyncClient denies custom region setting

### ISSUE THREAD

**Issue by ostronom** [MfgLabs/commons-aws#26]
It is not possible to provide your own region programmatically (or even an endpoint). Can you make `AmazonS3AsyncClient` into a trait, so we can extend it?

**Comment by Timshel** [comment]
Hi,
You should switch to the last version `0.12.2`.
`AmazonS3AsyncClient` was renamed as `AmazonS3Client` and additional [hepers](http://mfglabs.github.io/commons-aws/api/current/com/mfglabs/commons/aws/s3/AmazonS3Client$.html) are provided.

**Comment by ostronom** [comment]
Thank you!
